export const DATABASE_ID = import.meta.env.VITE_DATABASE_ID;
export const INBOX_COLLECTION_ID = import.meta.env.VITE_INBOX_COLLECTION_ID;
export const NOTIFICATIONS_COLLECTION_ID = import.meta.env.VITE_NOTIFICATIONS_COLLECTION_ID;
export const VIEWS_COLLECTION_ID = import.meta.env.VITE_VIEWS_COLLECTION_ID;
export const CERTIFICATES_COLLECTION_ID = import.meta.env.VITE_CERTIFICATES_COLLECTION_ID